create database Patient_Tracking;
use Patient_Tracking;
create table role(id int NOT NULL,name varchar(20));
insert into role values(1,"User");
insert into role values(2,"Clerk");
insert into role values(3,"Doctor");
insert into role values(4,"patient");
create table User(id int auto_increment PRIMARY KEY,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),AGE INT,
GENDER VARCHAR(10),
PHONE_NUMBER INT NOT NULL);
CREATE TABLE MEDICINE_INFORMATION(MEDICINE_ID INT PRIMARY KEY,
MEDICINE_NAME VARCHAR(20) PRIMARY KEY,
PATIENT_ID INT PRIMARY KEY,
FOREIGN KEY(PATIENT_ID) REFERENCES USER(ID));
CREATE TABLE PRESCRIPTION_DETAILS(PRESCRIPTION_ID INT PRIMARY KEY,
MEDICINE_NAME VARCHAR(20), 
QUANTITY INT, 
PATIENT_NAME VARCHAR(20),
FOREIGN KEY(PATEINT_NAME) REFERENCES USER(FIRST_NAME));
CREATE TABLE BILL(MEDICINE_NAME VARCHAR(20),AMOUNT INT,OUANTITY INT);

